name: Tests
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main

jobs:
  cmake-config:
    name: CMake config check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Check CMake 3.10
      uses: ./.github/actions/quick_cmake
      with:
        cmake-version: "3.10"
      if: success() || failure()

    - name: Check CMake 3.11
      uses: ./.github/actions/quick_cmake
      with:
        cmake-version: "3.11"
      if: success() || failure()

    - name: Check CMake 3.12
      uses: ./.github/actions/quick_cmake
      with:
        cmake-version: "3.12"
      if: success() || failure()

    - name: Check CMake 3.13
      uses: ./.github/actions/quick_cmake
      with:
        cmake-version: "3.13"
      if: success() || failure()

    - name: Check CMake 3.14
      uses: ./.github/actions/quick_cmake
      with:
        cmake-version: "3.14"
      if: success() || failure()

    - name: Check CMake 3.15
      uses: ./.github/actions/quick_cmake
      with:
        cmake-version: "3.15"
      if: success() || failure()

    - name: Check CMake 3.16
      uses: ./.github/actions/quick_cmake
      with:
        cmake-version: "3.16"
      if: success() || failure()

    - name: Check CMake 3.17
      uses: ./.github/actions/quick_cmake
      with:
        cmake-version: "3.17"
      if: success() || failure()

    - name: Check CMake 3.18
      uses: ./.github/actions/quick_cmake
      with:
        cmake-version: "3.18"
      if: success() || failure()

    - name: Check CMake 3.19
      uses: ./.github/actions/quick_cmake
      with:
        cmake-version: "3.19"
      if: success() || failure()

    - name: Check CMake 3.20
      uses: ./.github/actions/quick_cmake
      with:
        cmake-version: "3.20"
      if: success() || failure()

    - name: Check CMake 3.21
      uses: ./.github/actions/quick_cmake
      with:
        cmake-version: "3.21"
      if: success() || failure()

    - name: Check CMake 3.22
      uses: ./.github/actions/quick_cmake
      with:
        cmake-version: "3.22"
      if: success() || failure()
